### ISSUE TITLE
Version in the badge is not reflecting the actual version of the documentation

### ISSUE THREAD

**Issue by thromera** [bendtherules/webpack.js.org#1]
Original issue: https://github.com/webpack/webpack.js.org/issues/1961#issuecomment-479370015
continuing the conversation in here. 

> Actually, the source code has the unversioned badge from shields.io (like img.shields.io/npm/v/webpack.svg), which picks up the latest npm version.

I understand that the badge is coming from shields.io. It is a good idea to keep the code pristine, but for that one, I would suggest we change the badge version displayed to the actual version of the documentation (3.11.0), or replace the badge by a string directly, so it's not confusing. 

Thanks BTW for hosting the documentation.

**Comment by bendtherules** [comment]
Changing the link (to versioned one) makes sense to me. 

Have made this change.
Will close this after testing the deployment. 

[![Netlify Status](https://api.netlify.com/api/v1/badges/adc3f798-590f-424f-ace6-b725c96a5d28/deploy-status)](https://app.netlify.com/sites/webpack-v3/deploys)
